# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sportwb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sportwb

	pod 'AFNetworking', '~> 3.0'
	pod 'SVProgressHUD'
	pod 'MJRefresh'
  	pod 'Masonry'
  	pod 'Mantle' 
	pod ‘Reveal-SDK‘, ‘~> 4‘, :configurations => [‘Debug‘]
	pod 'KissXML', '5.0'
    pod 'SDWebImage', '3.8.1'

target 'sportwbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sportwbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
